// Master 3-level taxonomy (category > subcategory > microcategory) provided
// by the business team. Edit this file to add or rename taxonomy nodes; the
// seeder will upsert categories/subcategories/microcategories so existing IDs
// and any attached items are preserved.

export type TaxonomyRow = [category: string, subcategory: string, microcategory: string];

export const TAXONOMY: TaxonomyRow[] = [
  ['Alloy Steel', 'Alloy Steel Scrap', 'General Alloy Scrap'],
  ['Alloy Steel', 'Alloy Steel Scrap', 'Melting Scrap'],
  ['Alloy Steel', 'Alloy Steel Scrap', 'Turnings/Borings'],
  ['By-Products & Residues', 'Ash & Residues', 'Ash/Cenosphere'],
  ['By-Products & Residues', 'Coke & Carbon', 'Coke/Carbon Products'],
  ['By-Products & Residues', 'Dust & Fines', 'Industrial Dust'],
  ['By-Products & Residues', 'Mill Scale & Oxide', 'Mill Scale/Iron Oxide'],
  ['By-Products & Residues', 'Other Residues', 'Mixed Residues'],
  ['By-Products & Residues', 'Sand', 'Industrial Sand'],
  ['By-Products & Residues', 'Slag', 'Slag'],
  ['Cast Iron & DI', 'Cast Iron', 'CI Scrap'],
  ['Cast Iron & DI', 'Ductile Iron (DI)', 'DI Scrap'],
  ['Containers & Drums', 'MS Drums', 'Empty MS Drums'],
  ['Containers & Drums', 'MS Drums', 'MS Drums'],
  ['Containers & Drums', 'MS Drums', 'MS Drums/Tins'],
  ['Containers & Drums', 'Mixed Containers', 'Mixed Drums/Containers'],
  ['Containers & Drums', 'Plastic Containers', 'Plastic Drums/Cans'],
  ['Electrical & Electronics', 'Batteries', 'Battery Scrap'],
  ['Electrical & Electronics', 'Cables & Wires', 'Copper Cables'],
  ['Electrical & Electronics', 'Cables & Wires', 'Mixed Cables'],
  ['Electrical & Electronics', 'E-Waste', 'IT & Electronic Waste'],
  ['Electrical & Electronics', 'Electrical Misc', 'General Electrical Scrap'],
  ['Electrical & Electronics', 'Motors & Generators', 'Electric Motors'],
  ['Electrical & Electronics', 'Panels & Switchgear', 'Electrical Panels'],
  ['Flat Steel Products', 'BP Sheets', 'BP Arising Sheets'],
  ['Flat Steel Products', 'CQ Products', 'CQ CTL'],
  ['Flat Steel Products', 'CQ Products', 'CQ Coils'],
  ['Flat Steel Products', 'CQ Products', 'CQ Wider/Rim'],
  ['Flat Steel Products', 'CQ Products', 'Other CQ'],
  ['Flat Steel Products', 'CR Products', 'Baby Coils'],
  ['Flat Steel Products', 'CR Products', 'CR Process Scrap'],
  ['Flat Steel Products', 'CR Products', 'CR Scrap'],
  ['Flat Steel Products', 'CR Products', 'Coil Cutting'],
  ['Flat Steel Products', 'CR Products', 'Coil Ends/Leaders'],
  ['Flat Steel Products', 'CR Products', 'Coils'],
  ['Flat Steel Products', 'CR Products', 'End Cuts'],
  ['Flat Steel Products', 'CR Products', 'Full Hard Coils'],
  ['Flat Steel Products', 'CR Products', 'Other CR Products'],
  ['Flat Steel Products', 'CR Products', 'Prime/Pickled Coils'],
  ['Flat Steel Products', 'CR Products', 'Sheets/CTL'],
  ['Flat Steel Products', 'CR Products', 'Side Trimming'],
  ['Flat Steel Products', 'CR Products', 'Slit/Defective Coils'],
  ['Flat Steel Products', 'Coil Processing Scrap', 'Coil End Cuts'],
  ['Flat Steel Products', 'Coil Processing Scrap', 'Side Cutting/Trimming'],
  ['Flat Steel Products', 'Coil Processing Scrap', 'Slit Coils'],
  ['Flat Steel Products', 'Colour Coated Products', 'Colour Coils'],
  ['Flat Steel Products', 'Colour Coated Products', 'Colour Corrugated Sheets'],
  ['Flat Steel Products', 'Colour Coated Products', 'Colour Plain Sheets'],
  ['Flat Steel Products', 'Colour Coated Products', 'Colour Profile Sheets'],
  ['Flat Steel Products', 'Colour Coated Products', 'Colour Trimming/Scrap'],
  ['Flat Steel Products', 'Colour Coated Products', 'Other Colour Coated'],
  ['Flat Steel Products', 'Electro-Galvanized/GA', 'EG/GA Coils & Sheets'],
  ['Flat Steel Products', 'Galvalume Products', 'Defective Coils'],
  ['Flat Steel Products', 'Galvalume Products', 'GL Coils'],
  ['Flat Steel Products', 'Galvalume Products', 'GL Corrugated Sheets'],
  ['Flat Steel Products', 'Galvalume Products', 'GL Plain Sheets'],
  ['Flat Steel Products', 'Galvalume Products', 'GL Profile Sheets'],
  ['Flat Steel Products', 'Galvalume Products', 'GL Trimming/Scrap'],
  ['Flat Steel Products', 'Galvalume Products', 'Other GL'],
  ['Flat Steel Products', 'Galvanized Products', 'GC Sheets'],
  ['Flat Steel Products', 'Galvanized Products', 'GI/GP Coils'],
  ['Flat Steel Products', 'Galvanized Products', 'GI/GP Sheets'],
  ['Flat Steel Products', 'HR Products', 'API Grade Coils'],
  ['Flat Steel Products', 'HR Products', 'Baby Coils'],
  ['Flat Steel Products', 'HR Products', 'Coil Cutting Scrap'],
  ['Flat Steel Products', 'HR Products', 'Coil Ends'],
  ['Flat Steel Products', 'HR Products', 'Coils'],
  ['Flat Steel Products', 'HR Products', 'End Cuts'],
  ['Flat Steel Products', 'HR Products', 'HR Scrap'],
  ['Flat Steel Products', 'HR Products', 'Other HR Products'],
  ['Flat Steel Products', 'HR Products', 'Prime Coils'],
  ['Flat Steel Products', 'HR Products', 'Rejected Coils'],
  ['Flat Steel Products', 'HR Products', 'Sheets/Plates/CTL'],
  ['Flat Steel Products', 'HR Products', 'Side Trimming/Slitting'],
  ['Flat Steel Products', 'HR Products', 'Slit Coils'],
  ['Flat Steel Products', 'HR Products', 'Strips/Patti'],
  ['Industrial Equipment', 'Heavy Equipment', 'Cranes'],
  ['Industrial Equipment', 'Machinery', 'General Machinery'],
  ['Industrial Equipment', 'Material Handling', 'Conveyors'],
  ['Industrial Equipment', 'Material Handling', 'Forklifts'],
  ['Industrial Equipment', 'Power Equipment', 'Generators/DG Sets'],
  ['Industrial Equipment', 'Power Equipment', 'Transformers'],
  ['Industrial Equipment', 'Process Equipment', 'Compressors'],
  ['Industrial Equipment', 'Process Equipment', 'Pumps'],
  ['Industrial Equipment', 'Rolls & Dies', 'Scrap Dies'],
  ['Industrial Equipment', 'Rolls & Dies', 'Used/Rejected Rolls'],
  ['Infrastructure & Structures', 'Portable Structures', 'Bunk Houses/Cabins'],
  ['MS Scrap', 'MS Melting Scrap', 'General MS Scrap'],
  ['MS Scrap', 'MS Melting Scrap', 'General Melting Scrap'],
  ['MS Scrap', 'MS Melting Scrap', 'Heavy Scrap'],
  ['MS Scrap', 'MS Melting Scrap', 'Light Scrap'],
  ['MS Scrap', 'MS Melting Scrap', 'Mixed MS Scrap'],
  ['MS Scrap', 'MS Packing Material', 'Packing Strips/Patti'],
  ['MS Scrap', 'MS Plates & Sheets', 'MS Plates/Sheets'],
  ['MS Scrap', 'MS Process Scrap', 'Tab/End Scrap'],
  ['MS Scrap', 'MS Process Scrap', 'Turning/Boring/Chips'],
  ['MS Scrap', 'MS Structural Scrap', 'Structural Scrap'],
  ['MS Scrap', 'MS Wire & Rope', 'MS Wire'],
  ['MS Scrap', 'MS Wire & Rope', 'Wire Rope'],
  ['Miscellaneous', 'Filters', 'Filter Scrap'],
  ['Miscellaneous', 'General Scrap', 'Mixed/Unclassified Scrap'],
  ['Miscellaneous', 'Glass', 'Glass Scrap'],
  ['Miscellaneous', 'Unclassified', 'Other Materials'],
  ['Non-Ferrous Metals', 'Aluminium', 'Cables & Wires'],
  ['Non-Ferrous Metals', 'Aluminium', 'Casting Scrap'],
  ['Non-Ferrous Metals', 'Aluminium', 'Chips/Turnings'],
  ['Non-Ferrous Metals', 'Aluminium', 'Dross'],
  ['Non-Ferrous Metals', 'Aluminium', 'Foil Scrap'],
  ['Non-Ferrous Metals', 'Aluminium', 'Mixed Aluminium Scrap'],
  ['Non-Ferrous Metals', 'Aluminium', 'Sheets/Strips/Coils'],
  ['Non-Ferrous Metals', 'Brass', 'Mixed Brass Scrap'],
  ['Non-Ferrous Metals', 'Copper', 'Cables & Wires'],
  ['Non-Ferrous Metals', 'Copper', 'Dust/Powder'],
  ['Non-Ferrous Metals', 'Copper', 'Mixed Copper Scrap'],
  ['Non-Ferrous Metals', 'Copper', 'Pipes & Tubes'],
  ['Non-Ferrous Metals', 'Copper', 'Turnings/Chips'],
  ['Non-Ferrous Metals', 'Gun Metal/Bronze', 'Gun Metal/Bronze Scrap'],
  ['Non-Ferrous Metals', 'Zinc', 'Other Zinc Scrap'],
  ['Non-Ferrous Metals', 'Zinc', 'Zinc Dross'],
  ['Non-Ferrous Metals', 'Zinc', 'Zinc Dust/Ash'],
  ['Office & Furniture', 'Furniture', 'Furniture Scrap'],
  ['Oils & Chemicals', 'Chemical Waste', 'General Chemical Waste'],
  ['Oils & Chemicals', 'Paints & Coatings', 'Paint/Primer Scrap'],
  ['Oils & Chemicals', 'Solvents', 'Spent Solvents'],
  ['Oils & Chemicals', 'Used Oils', 'Waste Grease'],
  ['Oils & Chemicals', 'Used Oils', 'Waste/Used Oil'],
  ['Plastics & Polymers', 'Epoxy/Coating', 'Epoxy Scrap'],
  ['Plastics & Polymers', 'HDPE', 'HDPE Scrap'],
  ['Plastics & Polymers', 'Mixed Plastics', 'General Plastic Scrap'],
  ['Plastics & Polymers', 'PP', 'PP Scrap'],
  ['Plastics & Polymers', 'PVC', 'PVC Scrap'],
  ['Refractory & Bricks', 'Refractory Material', 'Refractory/Brick Scrap'],
  ['Rubber & Tyres', 'Rubber Products', 'General Rubber Scrap'],
  ['Rubber & Tyres', 'Rubber Products', 'Hose Pipes'],
  ['Rubber & Tyres', 'Tyres', 'Tyre Scrap'],
  ['Safety & PPE', 'Safety Equipment', 'PPE & Safety Scrap'],
  ['Solar & Renewable', 'Solar Modules', 'Solar Panel/Cell Scrap'],
  ['Stainless Steel', 'SS Coils & Sheets', 'End Cuts'],
  ['Stainless Steel', 'SS Coils & Sheets', 'Other Coils'],
  ['Stainless Steel', 'SS Coils & Sheets', 'Prime Coils'],
  ['Stainless Steel', 'SS Coils & Sheets', 'Sheets'],
  ['Stainless Steel', 'SS Coils & Sheets', 'Slit Coils'],
  ['Stainless Steel', 'SS Pipes (General)', 'Mixed/Other'],
  ['Stainless Steel', 'SS Pipes (General)', 'Prime'],
  ['Stainless Steel', 'SS Pipes (General)', 'Short Length'],
  ['Stainless Steel', 'SS Plates', 'Plates'],
  ['Stainless Steel', 'SS Plates', 'Side Cutting'],
  ['Stainless Steel', 'SS Process Scrap', 'Discard/End Cuts'],
  ['Stainless Steel', 'SS Process Scrap', 'Milling/Facing Chips'],
  ['Stainless Steel', 'SS Process Scrap', 'Peeling Scrap'],
  ['Stainless Steel', 'SS Process Scrap', 'Plug/Mandrel Scrap'],
  ['Stainless Steel', 'SS Process Scrap', 'Sample Cutting'],
  ['Stainless Steel', 'SS Process Scrap', 'Turning/Boring'],
  ['Stainless Steel', 'SS Scrap', 'General SS Scrap'],
  ['Stainless Steel', 'SS Scrap', 'Mixed SS Scrap'],
  ['Stainless Steel', 'SS Seamless Pipes', 'End Cuts/Scrap'],
  ['Stainless Steel', 'SS Seamless Pipes', 'Hollow'],
  ['Stainless Steel', 'SS Seamless Pipes', 'Mixed/Other'],
  ['Stainless Steel', 'SS Seamless Pipes', 'Prime'],
  ['Stainless Steel', 'SS Seamless Pipes', 'Short Length'],
  ['Stainless Steel', 'SS Semi-Finished', 'Hollow Billets'],
  ['Stainless Steel', 'SS Semi-Finished', 'Hollows'],
  ['Stainless Steel', 'SS Semi-Finished', 'Rejected Hollows'],
  ['Stainless Steel', 'SS Welded Pipes', 'Mixed/Other'],
  ['Stainless Steel', 'SS Welded Pipes', 'Prime'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Brinting'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Fresh'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Fresh Rusty/Pitted'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Mixed/Other'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Pipe Cutting/Melting Scrap'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Rejected'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Rejected - Open Seam'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Rejected with Brinting'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Rusty/Pitted'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Short Length'],
  ['Steel Pipes & Tubes', 'Black Round Pipes', 'Surplus'],
  ['Steel Pipes & Tubes', 'CS Pipe End Cuts', 'Pipe End Cuts'],
  ['Steel Pipes & Tubes', 'CS Pipes', 'Commercial/Non-Prime'],
  ['Steel Pipes & Tubes', 'CS Pipes', 'Non-Prime Pipes'],
  ['Steel Pipes & Tubes', 'Drill Pipes & Collars', 'Commercial Grade'],
  ['Steel Pipes & Tubes', 'Drill Pipes & Collars', 'Drill Collars'],
  ['Steel Pipes & Tubes', 'Drill Pipes & Collars', 'Heavy Weight Drill Pipe'],
  ['Steel Pipes & Tubes', 'Drill Pipes & Collars', 'Standard Drill Pipe'],
  ['Steel Pipes & Tubes', 'ERW Pipes', 'Commercial Grade'],
  ['Steel Pipes & Tubes', 'ERW Pipes', 'Mixed/Other'],
  ['Steel Pipes & Tubes', 'ERW Pipes', 'Prime Coated'],
  ['Steel Pipes & Tubes', 'ERW Pipes', 'Prime Rusty/Pitted'],
  ['Steel Pipes & Tubes', 'ERW Pipes', 'Rejected - Crossweld/Window Cut'],
  ['Steel Pipes & Tubes', 'ERW Pipes', 'Rejected - General'],
  ['Steel Pipes & Tubes', 'ERW Pipes', 'Rejected - Pinhole/Open Seam'],
  ['Steel Pipes & Tubes', 'ERW Pipes', 'Rejected - Welding OK But Rejected'],
  ['Steel Pipes & Tubes', 'GI/GP Pipes', 'Dent/Bend/Defective'],
  ['Steel Pipes & Tubes', 'GI/GP Pipes', 'Fresh'],
  ['Steel Pipes & Tubes', 'GI/GP Pipes', 'Mixed/Other'],
  ['Steel Pipes & Tubes', 'GI/GP Pipes', 'Rejected'],
  ['Steel Pipes & Tubes', 'GI/GP Pipes', 'Short Length'],
  ['Steel Pipes & Tubes', 'GI/GP Pipes', 'Various Sizes'],
  ['Steel Pipes & Tubes', 'General Pipe Scrap', 'Pipe Cutting Scrap'],
  ['Steel Pipes & Tubes', 'General Pipe Scrap', 'Pipe End Cuts'],
  ['Steel Pipes & Tubes', 'General Pipe Scrap', 'Rejected Pipes'],
  ['Steel Pipes & Tubes', 'General Pipe Scrap', 'Unclassified Pipes'],
  ['Steel Pipes & Tubes', 'General Pipe Scrap', 'Various Sizes'],
  ['Steel Pipes & Tubes', 'Hollow Bloom', 'Alloy Steel'],
  ['Steel Pipes & Tubes', 'Hollow Bloom', 'Miss Roll/Defective'],
  ['Steel Pipes & Tubes', 'Hollow Bloom', 'Rejected'],
  ['Steel Pipes & Tubes', 'Hollow Bloom', 'Standard'],
  ['Steel Pipes & Tubes', 'LSAW Pipes', 'Coated'],
  ['Steel Pipes & Tubes', 'LSAW Pipes', 'Mixed/Other'],
  ['Steel Pipes & Tubes', 'LSAW Pipes', 'Prime'],
  ['Steel Pipes & Tubes', 'LSAW Pipes', 'Rejected'],
  ['Steel Pipes & Tubes', 'MS Pipes', 'MS Pipe Scrap'],
  ['Steel Pipes & Tubes', 'Pipe End Cuts (PEC)', 'Alloy Steel PEC'],
  ['Steel Pipes & Tubes', 'Pipe End Cuts (PEC)', 'General PEC'],
  ['Steel Pipes & Tubes', 'Pipe Fittings & Accessories', 'Old Couplings'],
  ['Steel Pipes & Tubes', 'Seamless Pipes (CS)', 'Alloy Grade'],
  ['Steel Pipes & Tubes', 'Seamless Pipes (CS)', 'Commercial Grade'],
  ['Steel Pipes & Tubes', 'Seamless Pipes (CS)', 'Mixed/Other'],
  ['Steel Pipes & Tubes', 'Seamless Pipes (CS)', 'Prime'],
  ['Steel Pipes & Tubes', 'Seamless Pipes (CS)', 'Prime Rusty/Pitted'],
  ['Steel Pipes & Tubes', 'Section Pipes (Square/Rect)', 'Black Section - Fresh'],
  ['Steel Pipes & Tubes', 'Section Pipes (Square/Rect)', 'Black Section - Rejected'],
  ['Steel Pipes & Tubes', 'Section Pipes (Square/Rect)', 'Black Section - Surplus'],
  ['Steel Pipes & Tubes', 'Section Pipes (Square/Rect)', 'Section - Mixed/Other'],
  ['Steel Pipes & Tubes', 'Section Pipes (Square/Rect)', 'Section - Open'],
  ['Steel Pipes & Tubes', 'Section Pipes (Square/Rect)', 'Section - Short Length'],
  ['Steel Pipes & Tubes', 'Section Pipes (Square/Rect)', 'Semi Prime Section'],
  ['Steel Pipes & Tubes', 'Spiral/HSAW Pipes', 'Coated'],
  ['Steel Pipes & Tubes', 'Spiral/HSAW Pipes', 'Commercial Grade'],
  ['Steel Pipes & Tubes', 'Spiral/HSAW Pipes', 'Fresh'],
  ['Steel Pipes & Tubes', 'Spiral/HSAW Pipes', 'Mixed/Other'],
  ['Steel Pipes & Tubes', 'Spiral/HSAW Pipes', 'Prime'],
  ['Steel Pipes & Tubes', 'Spiral/HSAW Pipes', 'Rejected'],
  ['Steel Pipes & Tubes', 'Spiral/HSAW Pipes', 'Surplus'],
  ['Steel Semi-Finished Products', 'Billets', 'CS Billet End Cuts'],
  ['Steel Semi-Finished Products', 'Billets', 'General Billets'],
  ['Steel Semi-Finished Products', 'Melting Scrap', 'CS Melting'],
  ['Steel Semi-Finished Products', 'Miss Roll Scrap', 'CS Miss Roll'],
  ['Steel Semi-Finished Products', 'Miss Roll Scrap', 'General Miss Roll'],
  ['Steel Semi-Finished Products', 'Pig Iron', 'Pig Iron'],
  ['Steel Semi-Finished Products', 'Rounds/Bars', 'Round Bars/Wire Rods'],
  ['Steel Semi-Finished Products', 'TMT/Rebars', 'TMT Bars'],
  ['Textile & Fabric', 'Textile Scrap', 'Cotton/Fabric Scrap'],
  ['Tools & Consumables', 'Abrasives', 'Grinding Wheel Scrap'],
  ['Tools & Consumables', 'Bearings', 'Bearing Scrap'],
  ['Tools & Consumables', 'Cutting Tools', 'Carbide Scrap'],
  ['Tools & Consumables', 'Cutting Tools', 'HSS Scrap'],
  ['Tools & Consumables', 'Cutting Tools', 'Saw/Blade Scrap'],
  ['Tools & Consumables', 'General Tools', 'Mixed Tool Scrap'],
  ['Tools & Consumables', 'Mechanical Parts', 'Gear Scrap'],
  ['Vehicles & Transport', 'Vehicles', 'Vehicle Scrap'],
  ['Wood & Paper', 'Paper & Cardboard', 'Paper/Cardboard Scrap'],
  ['Wood & Paper', 'Wooden Scrap', 'Wooden Scrap'],
];
